theme: jekyll-theme-time-machine
title: Text Adventures Suite
description: Text Adventures Suite is a authoring and interpreter of Text Adventures largely inspired on Steve Jackson and Ian Livingstone Fighting Fantasy series of game books in the 80s.
url: "https://ghostsysoutnull.github.io"
baseurl: "/tas-dist"
