theme: jekyll-theme-time-machine
title: "Text Adventures Suite - A Fighting Fantasy Application for Deskops"
url: "https://ghostsysoutnull.github.io" # the base hostname & protocol for your site
baseurl: "/tas-dist"
